<a href="https://colab.research.google.com/github/RishiBose04/DL-NN/blob/main/Vector_Addition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing packages
import tensorflow as tf
# creating a scalar
scalar = tf. constant(7)
scalar
scalar.ndim


0

In [4]:
# create a vector
vector = tf.constant([10, 10])
# checking the dimensions of vector
vector.ndim
# creating a matrix
matrix = tf.constant([[1, 2],[3, 4]])
print(matrix)
print("the number of dimensions of a matrix is:" +str(matrix.ndim))


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
the number of dimensions of a matrix is:2


In [5]:
# creating two tensors
matrix = tf.constant([[1, 2], [3, 4]])
matrix1 = tf.constant([[2, 4], [6, 8]])
# addition of two matrices
print(matrix + matrix1)
# subtraction of two matrices
print(matrix1 - matrix)
# multiplication of two matrices
print(matrix1 * matrix)
# division of two matrices
print(matrix1 / matrix)
# creating a matrix
matrix = tf.constant([[1, 2], (3, 4)])
print(matrix )

tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  8]
 [18 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
# transpose of the matrix
print(tf.transpose(matrix))
# dot product of matrices
print("dot product of matrices is : "+
str(tf.tensordot(matrix, matrix,axes= 1)))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
dot product of matrices is : tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
